- name: check if /root/.my.cnf pass is updated
  shell: grep 'Percona2017_' /root/.my.cnf
  register: value_root_pass
  failed_when: false
- name: temp mysql root password
  shell: >
    awk -F': ' '$0 ~ "temporary password"{print $2}' /var/lib/mysql/error.log
  register: mysql_root_temp_password
  when: value_root_pass.rc == 1 and (ansible_hostname == mysql_alter_57_password or mysql_alter_57_password == '*')
- name: change root password to temp
  lineinfile:
    dest: /root/.my.cnf
    regexp: '^password = '
    line: "password = '{{ mysql_root_temp_password.stdout }}'"
  when: value_root_pass.rc == 1 and (ansible_hostname == mysql_alter_57_password or mysql_alter_57_password == '*')
- name: alter root password
  shell: >
    mysql --connect-expired-password
    -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'Percona2017_'"
  when: value_root_pass.rc == 1 and (ansible_hostname == mysql_alter_57_password or mysql_alter_57_password == '*')
- name: update my.cnf with root password
  lineinfile:
    dest: /root/.my.cnf
    regexp: '^password = '
    line: 'password = Percona2017_'
  when: value_root_pass.rc == 1
