---
- name: upload mha sql grants
  template:
    src: ../files/setup-grants-mha.sql
    dest: /home/vagrant/.ansible/setup-grants-mha.sql
    owner: vagrant
    group: vagrant
    mode: 0644

- name: create mha mysql account
  shell: > 
    mysql -uroot < /home/vagrant/.ansible/setup-grants-mha.sql && 
    touch /home/vagrant/.ansible/.state_grants_mha_installed
  args:
    creates: /home/vagrant/.ansible/.state_grants_mha_installed

- name: vagrant .my.cnf for mhauser
  copy:
    src: ../templates/dot_my_mha.cnf
    dest: /home/vagrant/.my.cnf
    owner: vagrant
    group: vagrant
    mode: 0644
