---
- name: upload proxysql grants
  template:
    src: ../files/setup-proxysql.sql
    dest: /home/vagrant/.ansible/setup-proxysql.sql
    owner: vagrant
    group: vagrant
    mode: 0644

- name: percona .my.cnf for vagrant user
  template:
    src: ../templates/dot_my_proxysql.cnf
    dest: /home/vagrant/.my.cnf
    owner: vagrant
    group: vagrant
    mode: 0644

- name: create percona proxysql account
  shell: > 
    mysql --defaults-file=/home/vagrant/.my.cnf < /home/vagrant/.ansible/setup-proxysql.sql && 
    touch /home/vagrant/.ansible/.state_grants_installed
  args:
    creates: /home/vagrant/.ansible/.state_grants_installed

