---
- set_fact:
    mysql_server_package: 'Percona-XtraDB-Cluster'
  when: mysql_cluster_type is defined and mysql_cluster_type == 'pxc'
- name: remove conflicting mariadb-libs
  yum:
    name: mariadb-libs
    state: removed
- name: install client packages
  yum: 
    name: "{{ mysql_server_package }}-client{{ mysql_package }},{{ mysql_server_package }}-shared{{ mysql_package }},{{ mysql_server_package }}-shared-compat{{ mysql_package }}"
    update_cache: true
    state: present

- name: install extra client packages
  yum:
    name: percona-toolkit,nc,nmap,git,sysbench
    state: present

- name: /home/vagrant/.my.cnf mysql
  template:
    src: dot_my_percona.cnf
    dest: /home/vagrant/.my.cnf
    owner: vagrant
    group: vagrant
    mode: 0644