---
- name: upload sql grants
  template:
    src: setup-grants.sql
    dest: /home/vagrant/.ansible/setup-grants.sql
    owner: vagrant
    group: vagrant
    mode: 0644

- name: create percona mysql account
  shell: > 
    mysql -uroot < /home/vagrant/.ansible/setup-grants.sql && 
    touch /home/vagrant/.ansible/.state_grants_installed
  args:
    creates: /home/vagrant/.ansible/.state_grants_installed
