---
- set_fact:
    mysql_server_package: 'Percona-XtraDB-Cluster'
  when: mysql_cluster_type is defined and mysql_cluster_type == 'pxc'
- name: install server packages
  yum:
    name: "{{ mysql_server_package }}-server{{ mysql_package }}"
    update_cache: true
    state: present
- name: install extra server packages
  yum:
    name: percona-xtrabackup{{ xtrabackup_package }},libev,percona-toolkit,nc,nmap,git,qpress
    state: present
- name: create my.cnf file
  template:
    src: etc_my_template.cnf
    dest: /etc/my.cnf
    owner: mysql
    group: mysql
    mode: 0644
- name: start mysql server process
  service:
    enabled: yes
    state: started
    name: mysql
- name: /root/.my.cnf
  template:
    src: dot_my_root.cnf
    dest: /root/.my.cnf
    mode: 0600
    force: no
