---
- hosts: all
  tasks:
    - include: tasks/defaults.yml
  roles:
    - linux
    - client

- hosts: master
  roles:
    - { role: master, tags: ['async'] }

- hosts: mhaslaves
  roles:
    - { role: slave, tags: ['async'] }

- hosts: mha
  vars:
    mha_node_type: 'manager'
  roles:
    - { role: mha, tags: ['mha'] }

- hosts: mhanodes 
  vars:
    mha_node_type: 'node'
  roles:
    - { role: mha, tags: ['mha'] }
