---
- hosts: proxysqlnodes
  tasks:
  - include: tasks/repo-percona.yml
  - include: tasks/repo-epel.yml
  - include: tasks/linux-ssh.yml
  - include: tasks/linux-selinux.yml
  - name: install proxysql
    yum:
      name: https://github.com/sysown/proxysql/releases/download/v1.3.4/proxysql-1.3.4-1-centos7.x86_64.rpm
      state: present
  - name: install MySQL client
    yum: 
      name: Percona-Server-client-56
      update_cache: true
      state: present
  - name: ProxySQL service
    service:
      enabled: yes
      state: started
      name: proxysql
  - include: tasks/proxysql-accounts.yml
