---
- hosts: all
  tasks:    
  - include: tasks/repo-percona.yml
  - include: tasks/repo-epel.yml
  - include: tasks/linux-selinux.yml
  
- hosts: pxcnodes
  vars:
    mysql_package: '-57'
    xtrabackup_package: '-24'
    # * for all hosts, or ansible_hostname 
    # for specific hosts only
    mysql_alter_57_password: 'pxc01'
  tasks:
  - set_fact:
      mysql_package: '-56'
      xtrabackup_package: ''
    when: mysql_version == '5.6'
  - include: tasks/percona-cluster.yml
  - include: tasks/mysql-password-57.yml
    when: mysql_package == '-57'
  - include: tasks/mysql-accounts.yml

