---
- hosts: pxcnodes
  tasks:
    - include: tasks/defaults.yml
  vars:
    # * for all hosts, or ansible_hostname 
    # for specific hosts only
    mysql_alter_57_password: 'pxc01'
  roles:
    - server